### PR TITLE
ADD CONTACT US PAGE

### PR DESCRIPTION
**Pull request by imrishabhbansal**
CONTACT US PAGE FOR THE WEBSITE

Refers #7

### CODE REVIEW

**Review by utkarsh2102 — CHANGES_REQUESTED** [review]
Hey,
- Please squash the commits into one.
- Also, please include the screenshot of the page in the comments below.

**Comment by rb007123** [comment]
> 
> 
> CONTACT US PAGE FOR THE WEBSITE
> 
> Refers #7

- I have squashed all the commits.
- And here is the screenshot

**Comment by AniVerma17** [comment]
> 
Reduce the horizontal padding in the input fields.
Also, make width of input fields equal to that of submit button.

**Review by utkarsh2102 — CHANGES_REQUESTED** [review]
Hey,
Please roll back the last commit as it adds a lot of unwanted files to this PR.

**Comment by AniVerma17** [comment]
Closing this PR since the associated codebase has been removed now.

**Pull request closed without merging**
