### PR TITLE
Added Contact Us Page

### PR DESCRIPTION
**Pull request by udit-001**
Refers #7

Includes the Contact Us page for the website.

Contact Us Page

### CODE REVIEW

**Review by AniVerma17 — APPROVED** [review]
LGTM.

**Review by utkarsh2102 — CHANGES_REQUESTED** [review]
Hey,
The changes look good to me.
However, can you please squash your commits into one?

**Review by utkarsh2102 — CHANGES_REQUESTED** [review]
Hey,
Please roll back the latest commits.
That adds a lot of unwanted files here.

**Comment by AniVerma17** [comment]
Closing this PR since the associated codebase has been removed now.

**Pull request closed without merging**
